import './globals.css'
import { Inter } from 'next/font/google'
import { NextAuthSessionProvider } from './providers/sessionProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children }) {
  return (
    <html lang="en">
      <body className="">
      <NextAuthSessionProvider>
        {children}
      </NextAuthSessionProvider>
      </body>
    </html>
  )
}
